Repository uprm-inso4116-2025-2026-s1/semester-project-uprm_professional_portfolio, pull requests merged in 2025-09, with the labels that each got.

#67 Add Scope & Span based on A3
  docs/Milestone-1.adoc
Labels: documentation, Documentation Team

#82 Sections 1.2.3 ideas, 2.1.3 domain terminology and 2.1.6 function signatures
  docs/Milestone-1.adoc
Labels: Documentation Team

#96 2.3 implementation
  docs/Milestone-1.adoc
Labels: Documentation Team

#99 terminology section
  docs/Milestone-1.adoc
Labels: Documentation Team

#105 Added section 2.2.5 Machine Requirements to Milestone 1 Documentation
  docs/Milestone-1.adoc
Labels: documentation, Task Completed

#109 Completed LTT #106: Ubiquitous Language Glossary
  docs/ubiquitous-language.md
Labels: documentation, Task Completed, Lecture Topic Task
